use_frameworks!
platform :ios, '10.0'

target 'XCUILib_Example' do
  pod 'XCUILib', :path => '../'
#  target 'XCUILib_Tests' do
#    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#  end

  target 'XCUILib_ExampleUITests'
end

#target 'XCUILib_ExampleUITests' do
#  pod 'XCUILib', :path => '../'
#end 
